framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
            crowdin:
                dsn: '%env(CROWDIN_DSN)%'
                domains: ['messages']
                locales: ['fr','en']
                # Rajouter it et sp lorsque les traductions auront été faites
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
